/** @type {import('./index.js').GameSystemProfile} */
export const dnd5eProfile = Object.freeze({
  SYSTEM_ID: "dnd5e",
  SYSTEM_NAME: "D&D 5th Edition",

  STANDARD_CONDITIONS: Object.freeze(
    [
      "Grappled",
      "Restrained",
      "Prone",
      "Poisoned",
      "Stunned",
      "Blinded",
      "Charmed",
      "Frightened",
      "Incapacitated",
      "Invisible",
      "Paralyzed",
      "Petrified",
      "Unconscious",
    ].sort((a, b) => a.localeCompare(b)),
  ),

  CONDITION_DATA: Object.freeze({
    Grappled: { past: "grappled", verb: "grapples", icon: "[G]", emoji: "🤛" },
    Restrained: { past: "restrained", verb: "restrains", icon: "[R]", emoji: "🔒" },
    Prone: { past: "knocked prone", verb: "knocks", suffix: "prone", icon: "[P]", emoji: "🛌" },
    Poisoned: { past: "poisoned", verb: "poisons", icon: "[Psn]", emoji: "☠️" },
    Stunned: { past: "stunned", verb: "stuns", icon: "[Stn]", emoji: "😵" },
    Blinded: { past: "blinded", verb: "blinds", icon: "[B]", emoji: "🙈" },
    Charmed: { past: "charmed", verb: "charms", icon: "[C]", emoji: "😍" },
    Frightened: { past: "frightened", verb: "frightens", icon: "[F]", emoji: "😱" },
    Incapacitated: { past: "incapacitated", verb: "incapacitates", icon: "[I]", emoji: "🚫" },
    Invisible: { past: "invisible", verb: "makes", suffix: "invisible", icon: "[Inv]", emoji: "🥷" },
    Paralyzed: { past: "paralyzed", verb: "paralyzes", icon: "[Pz]", emoji: "❄️" },
    Petrified: { past: "petrified", verb: "petrifies", icon: "[Pet]", emoji: "🪨" },
    Unconscious: { past: "unconscious", verb: "knocks", suffix: "unconscious", icon: "[U]", emoji: "💤" },
    Spell: { past: "affected by a spell", verb: "casts a spell on", icon: "[Spl]", emoji: "🔮" },
    Ability: { past: "affected by an ability", verb: "uses an ability on", icon: "[Abl]", emoji: "🎯" },
    Advantage: { past: "has advantage", verb: "grants advantage to", icon: "[Adv]", emoji: "🍀", noBy: true },
    Disadvantage: { past: "has disadvantage", verb: "imposes disadvantage on", icon: "[Dis]", emoji: "⬇️", noBy: true },
  }),

  DEFAULT_MARKERS: Object.freeze({
    Grappled: "grab",
    Restrained: "padlock",
    Prone: "back-pain",
    Poisoned: "chemical-bolt",
    Stunned: "pummeled",
    Blinded: "bleeding-eye",
    Charmed: "chained-heart",
    Frightened: "screaming",
    Incapacitated: "interdiction",
    Invisible: "ninja-mask",
    Paralyzed: "frozen-orb",
    Petrified: "fossil",
    Unconscious: "sleepy",
    Spell: "lightning-helix",
    Ability: "fist",
    Advantage: "three-leaves",
    Disadvantage: "broken-heart",
  }),

  CUSTOM_EFFECT_TYPES: Object.freeze(["Spell", "Ability", "Advantage", "Disadvantage", "Other"]),
  CUSTOM_EFFECT_LABELS: Object.freeze({}),
});
