/** @type {import('./index.js').GameSystemProfile} */
export const pathfinder2eProfile = Object.freeze({
  SYSTEM_ID: "pathfinder2e",
  SYSTEM_NAME: "Pathfinder 2nd Edition",

  STANDARD_CONDITIONS: Object.freeze(
    [
      "Blinded",
      "Clumsy",
      "Concealed",
      "Confused",
      "Controlled",
      "Dazzled",
      "Deafened",
      "Doomed",
      "Drained",
      "Dying",
      "Encumbered",
      "Enfeebled",
      "Fascinated",
      "Fatigued",
      "Fleeing",
      "Frightened",
      "Grabbed",
      "Hidden",
      "Immobilized",
      "Invisible",
      "Off-Guard",
      "Paralyzed",
      "Petrified",
      "Prone",
      "Quickened",
      "Restrained",
      "Sickened",
      "Slowed",
      "Stunned",
      "Stupefied",
      "Unconscious",
      "Undetected",
      "Wounded",
    ].sort((a, b) => a.localeCompare(b)),
  ),

  CONDITION_DATA: Object.freeze({
    Blinded: { past: "blinded", verb: "blinds", icon: "[B]", emoji: "🙈" },
    Clumsy: { past: "clumsy", verb: "makes", suffix: "clumsy", icon: "[Cl]", emoji: "🤦" },
    Concealed: { past: "concealed", verb: "conceals", icon: "[Cnc]", emoji: "🌫️" },
    Confused: { past: "confused", verb: "confuses", icon: "[Con]", emoji: "🤪" },
    Controlled: { past: "controlled", verb: "controls", icon: "[Ctrl]", emoji: "🧠" },
    Dazzled: { past: "dazzled", verb: "dazzles", icon: "[Dzl]", emoji: "✨" },
    Deafened: { past: "deafened", verb: "deafens", icon: "[Df]", emoji: "🙉" },
    Doomed: { past: "doomed", verb: "dooms", icon: "[Dm]", emoji: "💀" },
    Drained: { past: "drained", verb: "drains", icon: "[Dr]", emoji: "🩸" },
    Dying: { past: "dying", verb: "knocks", suffix: "dying", icon: "[Dy]", emoji: "☠️" },
    Encumbered: { past: "encumbered", verb: "encumbers", icon: "[Enc]", emoji: "🎒" },
    Enfeebled: { past: "enfeebled", verb: "enfeebles", icon: "[Enf]", emoji: "💪" },
    Fascinated: { past: "fascinated", verb: "fascinates", icon: "[Fas]", emoji: "🌀" },
    Fatigued: { past: "fatigued", verb: "fatigues", icon: "[Fat]", emoji: "😫" },
    Fleeing: { past: "fleeing", verb: "causes", suffix: "to flee", icon: "[Fle]", emoji: "🏃" },
    Frightened: { past: "frightened", verb: "frightens", icon: "[Fr]", emoji: "😱" },
    Grabbed: { past: "grabbed", verb: "grabs", icon: "[Gr]", emoji: "🤛" },
    Hidden: { past: "hidden", verb: "hides", icon: "[Hid]", emoji: "🕵️" },
    Immobilized: { past: "immobilized", verb: "immobilizes", icon: "[Imm]", emoji: "⛓️" },
    Invisible: { past: "invisible", verb: "makes", suffix: "invisible", icon: "[Inv]", emoji: "🥷" },
    "Off-Guard": { past: "off-guard", verb: "catches", suffix: "off-guard", icon: "[OG]", emoji: "🛡️" },
    Paralyzed: { past: "paralyzed", verb: "paralyzes", icon: "[Pz]", emoji: "❄️" },
    Petrified: { past: "petrified", verb: "petrifies", icon: "[Pet]", emoji: "🪨" },
    Prone: { past: "knocked prone", verb: "knocks", suffix: "prone", icon: "[P]", emoji: "🛌" },
    Quickened: { past: "quickened", verb: "quickens", icon: "[Qck]", emoji: "⚡" },
    Restrained: { past: "restrained", verb: "restrains", icon: "[R]", emoji: "🔒" },
    Sickened: { past: "sickened", verb: "sickens", icon: "[Sk]", emoji: "🤢" },
    Slowed: { past: "slowed", verb: "slows", icon: "[Sl]", emoji: "🐢" },
    Stunned: { past: "stunned", verb: "stuns", icon: "[Stn]", emoji: "😵" },
    Stupefied: { past: "stupefied", verb: "stupefies", icon: "[Stu]", emoji: "🤯" },
    Unconscious: { past: "unconscious", verb: "knocks", suffix: "unconscious", icon: "[U]", emoji: "💤" },
    Undetected: { past: "undetected", verb: "makes", suffix: "undetected", icon: "[Und]", emoji: "👻" },
    Wounded: { past: "wounded", verb: "wounds", icon: "[Wnd]", emoji: "🩹" },
    Spell: { past: "affected by a spell", verb: "casts a spell on", icon: "[Spl]", emoji: "🔮" },
    Ability: { past: "affected by an ability", verb: "uses an ability on", icon: "[Abl]", emoji: "🎯" },
  }),

  DEFAULT_MARKERS: Object.freeze({
    Blinded: "bleeding-eye",
    Clumsy: "back-pain",
    Concealed: "ninja-mask",
    Confused: "interdiction",
    Controlled: "chained-heart",
    Dazzled: "edge-crack",
    Deafened: "edge-crack",
    Doomed: "skull",
    Drained: "half-heart",
    Dying: "skull",
    Encumbered: "grab",
    Enfeebled: "half-heart",
    Fascinated: "chained-heart",
    Fatigued: "sleepy",
    Fleeing: "screaming",
    Frightened: "screaming",
    Grabbed: "grab",
    Hidden: "ninja-mask",
    Immobilized: "padlock",
    Invisible: "ninja-mask",
    "Off-Guard": "overdrive",
    Paralyzed: "frozen-orb",
    Petrified: "fossil",
    Prone: "back-pain",
    Quickened: "lightning-helix",
    Restrained: "padlock",
    Sickened: "chemical-bolt",
    Slowed: "snail",
    Stunned: "pummeled",
    Stupefied: "interdiction",
    Unconscious: "sleepy",
    Undetected: "ninja-mask",
    Wounded: "half-heart",
    Spell: "lightning-helix",
    Ability: "fist",
  }),

  // PF2e has no Advantage/Disadvantage mechanic
  CUSTOM_EFFECT_TYPES: Object.freeze(["Spell", "Ability", "Other"]),
  CUSTOM_EFFECT_LABELS: Object.freeze({}),
});
