/** @type {import('./index.js').GameSystemProfile} */
export const pathfinder1eProfile = Object.freeze({
  SYSTEM_ID: 'pathfinder1e',
  SYSTEM_NAME: 'Pathfinder First Edition',

  STANDARD_CONDITIONS: Object.freeze(
    [
      'Bleed',
      'Blinded',
      'Broken',
      'Confused',
      'Cowering',
      'Dazed',
      'Dazzled',
      'Deafened',
      'Disabled',
      'Dying',
      'Energy Drained',
      'Entangled',
      'Exhausted',
      'Fascinated',
      'Fatigued',
      'Flat-Footed',
      'Frightened',
      'Grappled',
      'Helpless',
      'Invisible',
      'Nauseated',
      'Panicked',
      'Paralyzed',
      'Petrified',
      'Pinned',
      'Prone',
      'Shaken',
      'Sickened',
      'Staggered',
      'Stunned',
      'Unconscious',
    ].sort((a, b) => a.localeCompare(b))
  ),

  CONDITION_DATA: Object.freeze({
    Bleed: { past: 'bleeding', verb: 'causes', suffix: 'to bleed', icon: '[Bld]', emoji: '🩸' },
    Blinded: { past: 'blinded', verb: 'blinds', icon: '[B]', emoji: '🙈' },
    Broken: { past: 'broken', verb: 'breaks', icon: '[Brk]', emoji: '💔' },
    Confused: { past: 'confused', verb: 'confuses', icon: '[Con]', emoji: '🤪' },
    Cowering: { past: 'cowering', verb: 'causes', suffix: 'to cower', icon: '[Cwr]', emoji: '😰' },
    Dazed: { past: 'dazed', verb: 'dazes', icon: '[Dz]', emoji: '😵' },
    Dazzled: { past: 'dazzled', verb: 'dazzles', icon: '[Dzl]', emoji: '✨' },
    Deafened: { past: 'deafened', verb: 'deafens', icon: '[Df]', emoji: '🙉' },
    Disabled: { past: 'disabled', verb: 'disables', icon: '[Dis]', emoji: '🚑' },
    Dying: { past: 'dying', verb: 'knocks', suffix: 'dying', icon: '[Dy]', emoji: '💀' },
    'Energy Drained': { past: 'energy drained', verb: 'drains', icon: '[ED]', emoji: '🌑' },
    Entangled: { past: 'entangled', verb: 'entangles', icon: '[Ent]', emoji: '🕸️' },
    Exhausted: { past: 'exhausted', verb: 'exhausts', icon: '[Ex]', emoji: '😩' },
    Fascinated: { past: 'fascinated', verb: 'fascinates', icon: '[Fas]', emoji: '🌀' },
    Fatigued: { past: 'fatigued', verb: 'fatigues', icon: '[Fat]', emoji: '😫' },
    'Flat-Footed': {
      past: 'flat-footed',
      verb: 'catches',
      suffix: 'flat-footed',
      icon: '[FF]',
      emoji: '👟',
    },
    Frightened: { past: 'frightened', verb: 'frightens', icon: '[Fr]', emoji: '😱' },
    Grappled: { past: 'grappled', verb: 'grapples', icon: '[G]', emoji: '🤛' },
    Helpless: { past: 'helpless', verb: 'renders', suffix: 'helpless', icon: '[Hlp]', emoji: '🙏' },
    Invisible: {
      past: 'invisible',
      verb: 'makes',
      suffix: 'invisible',
      icon: '[Inv]',
      emoji: '🥷',
    },
    Nauseated: { past: 'nauseated', verb: 'nauseates', icon: '[Naus]', emoji: '🤢' },
    Panicked: { past: 'panicked', verb: 'causes', suffix: 'to panic', icon: '[Pan]', emoji: '😨' },
    Paralyzed: { past: 'paralyzed', verb: 'paralyzes', icon: '[Pz]', emoji: '❄️' },
    Petrified: { past: 'petrified', verb: 'petrifies', icon: '[Pet]', emoji: '🪨' },
    Pinned: { past: 'pinned', verb: 'pins', icon: '[Pin]', emoji: '📌' },
    Prone: { past: 'knocked prone', verb: 'knocks', suffix: 'prone', icon: '[P]', emoji: '🛌' },
    Shaken: { past: 'shaken', verb: 'shakes', icon: '[Shk]', emoji: '😨' },
    Sickened: { past: 'sickened', verb: 'sickens', icon: '[Sk]', emoji: '🤢' },
    Staggered: { past: 'staggered', verb: 'staggers', icon: '[Stg]', emoji: '🥴' },
    Stunned: { past: 'stunned', verb: 'stuns', icon: '[Stn]', emoji: '😵' },
    Unconscious: {
      past: 'unconscious',
      verb: 'knocks',
      suffix: 'unconscious',
      icon: '[U]',
      emoji: '💤',
    },
    Spell: { past: 'affected by a spell', verb: 'casts a spell on', icon: '[Spl]', emoji: '🔮' },
    Ability: {
      past: 'affected by an ability',
      verb: 'uses an ability on',
      icon: '[Abl]',
      emoji: '🎯',
    },
  }),

  DEFAULT_MARKERS: Object.freeze({
    Bleed: 'bleeding-eye',
    Blinded: 'bleeding-eye',
    Broken: 'broken-heart',
    Confused: 'interdiction',
    Cowering: 'screaming',
    Dazed: 'pummeled',
    Dazzled: 'edge-crack',
    Deafened: 'edge-crack',
    Disabled: 'half-heart',
    Dying: 'skull',
    'Energy Drained': 'death-zone',
    Entangled: 'cobweb',
    Exhausted: 'sleepy',
    Fascinated: 'chained-heart',
    Fatigued: 'half-heart',
    'Flat-Footed': 'overdrive',
    Frightened: 'screaming',
    Grappled: 'grab',
    Helpless: 'frozen-orb',
    Invisible: 'ninja-mask',
    Nauseated: 'chemical-bolt',
    Panicked: 'screaming',
    Paralyzed: 'frozen-orb',
    Petrified: 'fossil',
    Pinned: 'padlock',
    Prone: 'back-pain',
    Shaken: 'half-heart',
    Sickened: 'chemical-bolt',
    Staggered: 'pummeled',
    Stunned: 'pummeled',
    Unconscious: 'sleepy',
    Spell: 'lightning-helix',
    Ability: 'fist',
  }),

  CUSTOM_EFFECT_TYPES: Object.freeze(['Spell', 'Ability', 'Other']),
  CUSTOM_EFFECT_LABELS: Object.freeze({}),
});
