/** @type {import('./index.js').GameSystemProfile} */
export const sotdlProfile = Object.freeze({
  SYSTEM_ID: 'sotdl',
  SYSTEM_NAME: 'Shadow of the Demon Lord',

  STANDARD_CONDITIONS: Object.freeze(
    [
      'Blinded',
      'Compelled',
      'Dazed',
      'Deafened',
      'Diseased',
      'Fatigued',
      'Frightened',
      'Helpless',
      'Immobilized',
      'Impaired',
      'Poisoned',
      'Prone',
      'Slowed',
      'Stunned',
      'Unconscious',
    ].sort((a, b) => a.localeCompare(b))
  ),

  CONDITION_DATA: Object.freeze({
    Blinded: { past: 'blinded', verb: 'blinds', icon: '[B]', emoji: '🙈' },
    Compelled: { past: 'compelled', verb: 'compels', icon: '[Cmp]', emoji: '🎭' },
    Dazed: { past: 'dazed', verb: 'dazes', icon: '[Dz]', emoji: '😵' },
    Deafened: { past: 'deafened', verb: 'deafens', icon: '[Df]', emoji: '🙉' },
    Diseased: { past: 'diseased', verb: 'infects', icon: '[Di]', emoji: '🦠' },
    Fatigued: { past: 'fatigued', verb: 'fatigues', icon: '[Fat]', emoji: '😫' },
    Frightened: { past: 'frightened', verb: 'frightens', icon: '[Fr]', emoji: '😱' },
    Helpless: { past: 'helpless', verb: 'renders', suffix: 'helpless', icon: '[Hlp]', emoji: '🙏' },
    Immobilized: { past: 'immobilized', verb: 'immobilizes', icon: '[Im]', emoji: '🔗' },
    Impaired: { past: 'impaired', verb: 'impairs', icon: '[Imp]', emoji: '⚠️' },
    Poisoned: { past: 'poisoned', verb: 'poisons', icon: '[Psn]', emoji: '☠️' },
    Prone: { past: 'knocked prone', verb: 'knocks', suffix: 'prone', icon: '[P]', emoji: '🛌' },
    Slowed: { past: 'slowed', verb: 'slows', icon: '[Sl]', emoji: '🐌' },
    Stunned: { past: 'stunned', verb: 'stuns', icon: '[Stn]', emoji: '😵' },
    Unconscious: {
      past: 'unconscious',
      verb: 'knocks',
      suffix: 'unconscious',
      icon: '[U]',
      emoji: '💤',
    },
    Spell: { past: 'affected by a spell', verb: 'casts a spell on', icon: '[Spl]', emoji: '🔮' },
    Ability: {
      past: 'affected by an ability',
      verb: 'uses an ability on',
      icon: '[Abl]',
      emoji: '🎯',
    },
  }),

  DEFAULT_MARKERS: Object.freeze({
    Blinded: 'bleeding-eye',
    Compelled: 'chained-heart',
    Dazed: 'pummeled',
    Deafened: 'edge-crack',
    Diseased: 'chemical-bolt',
    Fatigued: 'half-heart',
    Frightened: 'screaming',
    Helpless: 'frozen-orb',
    Immobilized: 'padlock',
    Impaired: 'interdiction',
    Poisoned: 'chemical-bolt',
    Prone: 'back-pain',
    Slowed: 'snail',
    Stunned: 'pummeled',
    Unconscious: 'sleepy',
    Spell: 'lightning-helix',
    Ability: 'fist',
  }),

  CUSTOM_EFFECT_TYPES: Object.freeze(['Spell', 'Ability', 'Other']),
  CUSTOM_EFFECT_LABELS: Object.freeze({}),
});
