/** @type {import('./index.js').GameSystemProfile} */
export const starfinderProfile = Object.freeze({
  SYSTEM_ID: "starfinder",
  SYSTEM_NAME: "Starfinder",

  STANDARD_CONDITIONS: Object.freeze(
    [
      "Asleep",
      "Bleeding",
      "Blinded",
      "Burning",
      "Confused",
      "Cowering",
      "Dazzled",
      "Dead",
      "Deafened",
      "Dying",
      "Encumbered",
      "Exhausted",
      "Fascinated",
      "Fatigued",
      "Flat-Footed",
      "Frightened",
      "Grappled",
      "Helpless",
      "Nauseated",
      "Off-Kilter",
      "Off-Target",
      "Overburdened",
      "Panicked",
      "Paralyzed",
      "Pinned",
      "Prone",
      "Shaken",
      "Sickened",
      "Stable",
      "Staggered",
      "Stunned",
      "Unconscious",
    ].sort((a, b) => a.localeCompare(b)),
  ),

  CONDITION_DATA: Object.freeze({
    Asleep: { past: "asleep", verb: "puts", suffix: "to sleep", icon: "[Asl]", emoji: "💤" },
    Bleeding: { past: "bleeding", verb: "causes", suffix: "to bleed", icon: "[Bld]", emoji: "🩸" },
    Blinded: { past: "blinded", verb: "blinds", icon: "[B]", emoji: "🙈" },
    Burning: { past: "burning", verb: "sets", suffix: "on fire", icon: "[Burn]", emoji: "🔥" },
    Confused: { past: "confused", verb: "confuses", icon: "[Con]", emoji: "🤪" },
    Cowering: { past: "cowering", verb: "causes", suffix: "to cower", icon: "[Cwr]", emoji: "😰" },
    Dazzled: { past: "dazzled", verb: "dazzles", icon: "[Dzl]", emoji: "✨" },
    Dead: { past: "dead", verb: "kills", icon: "[†]", emoji: "💀" },
    Deafened: { past: "deafened", verb: "deafens", icon: "[Df]", emoji: "🙉" },
    Dying: { past: "dying", verb: "knocks", suffix: "dying", icon: "[Dy]", emoji: "☠️" },
    Encumbered: { past: "encumbered", verb: "encumbers", icon: "[Enc]", emoji: "🎒" },
    Exhausted: { past: "exhausted", verb: "exhausts", icon: "[Ex]", emoji: "😩" },
    Fascinated: { past: "fascinated", verb: "fascinates", icon: "[Fas]", emoji: "🌀" },
    Fatigued: { past: "fatigued", verb: "fatigues", icon: "[Fat]", emoji: "😫" },
    "Flat-Footed": { past: "flat-footed", verb: "catches", suffix: "flat-footed", icon: "[FF]", emoji: "👟" },
    Frightened: { past: "frightened", verb: "frightens", icon: "[Fr]", emoji: "😱" },
    Grappled: { past: "grappled", verb: "grapples", icon: "[G]", emoji: "🤛" },
    Helpless: { past: "helpless", verb: "renders", suffix: "helpless", icon: "[Hlp]", emoji: "🙏" },
    Nauseated: { past: "nauseated", verb: "nauseates", icon: "[Naus]", emoji: "🤢" },
    "Off-Kilter": { past: "off-kilter", verb: "knocks", suffix: "off-kilter", icon: "[OK]", emoji: "🌀" },
    "Off-Target": { past: "off-target", verb: "knocks", suffix: "off-target", icon: "[OT]", emoji: "🎯" },
    Overburdened: { past: "overburdened", verb: "overburdens", icon: "[OB]", emoji: "🏋️" },
    Panicked: { past: "panicked", verb: "causes", suffix: "to panic", icon: "[Pan]", emoji: "😨" },
    Paralyzed: { past: "paralyzed", verb: "paralyzes", icon: "[Pz]", emoji: "❄️" },
    Pinned: { past: "pinned", verb: "pins", icon: "[Pin]", emoji: "📌" },
    Prone: { past: "knocked prone", verb: "knocks", suffix: "prone", icon: "[P]", emoji: "🛌" },
    Shaken: { past: "shaken", verb: "shakes", icon: "[Shk]", emoji: "😨" },
    Sickened: { past: "sickened", verb: "sickens", icon: "[Sk]", emoji: "🤢" },
    Stable: { past: "stable", verb: "stabilizes", icon: "[Stb]", emoji: "⚕️" },
    Staggered: { past: "staggered", verb: "staggers", icon: "[Stg]", emoji: "🥴" },
    Stunned: { past: "stunned", verb: "stuns", icon: "[Stn]", emoji: "😵" },
    Unconscious: { past: "unconscious", verb: "knocks", suffix: "unconscious", icon: "[U]", emoji: "💤" },
    Spell: { past: "affected by a spell", verb: "casts a spell on", icon: "[Spl]", emoji: "🔮" },
    Ability: { past: "affected by an ability", verb: "uses an ability on", icon: "[Abl]", emoji: "🎯" },
  }),

  DEFAULT_MARKERS: Object.freeze({
    Asleep: "sleepy",
    Bleeding: "half-heart",
    Blinded: "bleeding-eye",
    Burning: "lightning-helix",
    Confused: "interdiction",
    Cowering: "screaming",
    Dazzled: "edge-crack",
    Dead: "skull",
    Deafened: "edge-crack",
    Dying: "skull",
    Encumbered: "grab",
    Exhausted: "sleepy",
    Fascinated: "chained-heart",
    Fatigued: "half-heart",
    "Flat-Footed": "overdrive",
    Frightened: "screaming",
    Grappled: "grab",
    Helpless: "frozen-orb",
    Nauseated: "chemical-bolt",
    "Off-Kilter": "back-pain",
    "Off-Target": "overdrive",
    Overburdened: "pummeled",
    Panicked: "screaming",
    Paralyzed: "frozen-orb",
    Pinned: "padlock",
    Prone: "back-pain",
    Shaken: "half-heart",
    Sickened: "chemical-bolt",
    Stable: "green",
    Staggered: "pummeled",
    Stunned: "pummeled",
    Unconscious: "sleepy",
    Spell: "lightning-helix",
    Ability: "fist",
  }),

  CUSTOM_EFFECT_TYPES: Object.freeze(["Spell", "Ability", "Other"]),
  CUSTOM_EFFECT_LABELS: Object.freeze({}),
});
