on('chat:message', function (msg) {
    /**
     * The GlitchCatcher is an API script that when added, will do its best
     * to catch Shadowrun glitches. In Shadowrun, any pooled roll which contains
     * more than half 1s is considered a glitch. In addition, if there are also
     * no hits on the roll, it is considered a critical glitch. When detected
     * glitches will be reported in the chat window.
     * 
     * The script does its best to avoid non-pooled rolls, but isn't
     * bulletproof. For instance, it avoids initiative rolls generated by any
     * character sheet roll template that starts with 'sr' and have whos content
     * contains the string 'Initiative'.
     * 
     * 
     * 
     */
     
    if((msg.type == 'general' && (msg.rolltemplate.indexOf('sr') == 0)) || msg.type == 'rollresult') { //todo JSON.parse(msg.content) to get the rollresult obj
        if(msg.content.indexOf('Initiative') >= 0) {
            return; //not a pooled roll, don't report glitches
        }
        if(msg.type == 'rollresult') {
            var rollResult = JSON.parse(msg.content);
            var poolSize = rollResult.rolls[0].dice;
            var dice = rollResult.rolls[0].results;
        } else {
            var poolSize = msg.inlinerolls[1].results.rolls[0].dice;
            var dice = msg.inlinerolls[1].results.rolls[0].results;
        }
        
        
        var oneCount = 0;
        var hitCount = 0;
        var i = 0;
        var r;
        
        
        for(i=0; i<dice.length; i++) {
            if(dice[i].v == 1) {
                oneCount++;
            }
            if(dice[i].v == 5 || dice[i].v == 6) {
                hitCount++;
            }
        }
        log(msg.who + " rolled " + oneCount +" out of " + poolSize);
        if(oneCount > poolSize/2 && hitCount == 0) {
            log(msg.who + " critically glitched");
            sendChat("player|"+msg.playerid, "/direct <big><strong>CRIT GLITCH!</strong></big>");
        } else if(oneCount > poolSize/2){
            log(msg.who + " glitched");
            sendChat("player|"+msg.playerid, "/direct <big><strong>GLITCH!</strong></big>");
        }
    }
    
});